### ISSUE TITLE
Internal server error on beeminder-calendar.herokuapp.com

### ISSUE THREAD

**Issue by anka-213** [palfrey/beeminder-calendar#5]
After pressing "Login to Beeminder" and allowing access I get to an url like http://beeminder-calendar.herokuapp.com/calendar/myusername?access_token=some_access_token, which just says "500 Internal Server Error" and no further information.

**Comment by palfrey** [comment]
This is probably an instance of #1 (or at least solutions to that are likely to give information about this)

**Comment by palfrey** [comment]
Now I've fixed #1, this should also be sorted...

**Comment by anka-213** [comment]
Yes it works now. Thanks!

sön 1 nov. 2015 kl 16:19 skrev Tom Parker <notifications@github.com>:
